export type {
  FileType,
  ParagraphType,
  AnnotationType,
  AnnotationStatus,
  DocumentMeta,
  Paragraph,
  ParsedDocument,
  Annotation,
  ReviewSummary,
  ConflictStatus,
  DecisionChoice,
  DiffLineType,
  DiffLine,
  ParagraphDiff,
  MergeConflict,
  MergeDecision,
  MergeHistoryEntry,
  MergeSession,
  MergeStats,
} from '../../shared/types';
